/*
 * This source file was generated by the Gradle 'init' task
 */
package operatedarocket;

import javax.swing.JFrame;
import javax.swing.UIManager;

import java.awt.Font;
import java.io.InputStream;

import com.formdev.flatlaf.themes.FlatMacLightLaf;

import operatedarocket.LotusOS.HomeScreen;

public class OperateDaRocketApplication {
    public static JFrame frame;

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new OperateDaRocketApplication().getGreeting());

        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }

        InputStream fontIS = OperateDaRocketApplication.class.getResourceAsStream("/fonts/JetBrainsMono-Regular.ttf");
        Font customFont;
        customFont = Font.createFont(Font.TRUETYPE_FONT, fontIS).deriveFont(12f);

        for (Object key : UIManager.getLookAndFeelDefaults().keySet()) {
            if (key != null && key.toString().endsWith(".font")) {
                UIManager.put(key, customFont);
            }
        }

        frame = new JFrame();
        frame.setContentPane(new HomeScreen());
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setTitle("Operate Da Rocket - Universe 0");
        frame.setUndecorated(true);
        frame.setVisible(true);
    }
}
